### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kiiinji** [Myrkie/BoothDownloader#22] opened 2024-12-07 18:39 UTC
I add my cookie and each time it says the cookie is invalid.

**Comment by Myrkie** [comment] 2024-12-07 18:43
which browser are you using?

**Comment by Kiiinji** [comment] 2024-12-07 18:45
Firefox

**Comment by Myrkie** [comment] 2024-12-07 18:49
after running booth downloader, try putting your token between the quotes in the auto generated config file `BDConfig.json` there seems to be a regression with the automatic parsing


`"Cookie": "TokenHere"`

**Comment by Myrkie** [comment] 2024-12-07 19:18
has been fixed in https://github.com/Myrkie/BoothDownloader/commit/806dab399907a773735cbd4c68b09caceaa25c16#diff-19c52bdefe4059b02df1f4282188d6a7aaf14e1293c2aa6408864f3093cf645cL14-R14 
booth seems to be applying more aggressive redirects with cloudflare can you verify [this](https://github.com/Myrkie/BoothDownloader/releases/tag/V10.0.4) build works?

**Comment by Kiiinji** [comment] 2024-12-07 20:07
It works but it won't download owned files, no matter if I use the URL or the "owned" command (owned returns a "no item found")

The only thing it downloads is images

**Comment by Kiiinji** [comment] 2024-12-07 20:09
![image](https://github.com/user-attachments/assets/13233cfc-beda-4525-8b10-a802a45fffaf)

**Comment by Myrkie** [comment] 2024-12-07 20:14
parsing may have broken, ill look into it another time, manually downloading items should work fine until then.

**Comment by Kiiinji** [comment] 2024-12-07 20:17
Manually? If you mean from the website it's not an option for me, for some reason booth will fail any download I try and lower my download speed to 15kb/s

**Comment by Myrkie** [comment] 2024-12-07 20:19
you can paste in the URL to the booth page and it will auto parse that way instead and download all items (if you own the items)

**Comment by Kiiinji** [comment] 2024-12-07 20:21
Not working, it only gets images (I used [this](https://booth.pm/en/items/3549042) link, and I own this item)
![image](https://github.com/user-attachments/assets/1e28262a-26a8-4cde-9673-0d254afc744f)

**Comment by Myrkie** [comment] 2024-12-07 20:24
is your cookie valid? im unable to reproduce this.

**Comment by Kiiinji** [comment] 2024-12-07 20:25
Yes
![image](https://github.com/user-attachments/assets/65899804-9e0d-4505-ada0-3bc042350103)

**Comment by Myrkie** [comment] 2024-12-07 20:32
ill continue to try to reproduce

**Comment by Kiiinji** [comment] 2024-12-07 20:33
This happens on all items, if this can help

**Comment by Kiiinji** [comment] 2024-12-07 20:36
And proof that I own the item provided as example:
![image](https://github.com/user-attachments/assets/44cb413f-8c96-40cb-8c9c-16acf3bb5f1f)

**Comment by Kiiinji** [comment] 2024-12-07 20:37
More informations:
Windows 10
Firefox V133
France (Europe)

**Comment by Kiiinji** [comment] 2024-12-07 20:41
Same issue when started as admin and on Firefox Developer edition (v134.0b7)

**Comment by Myrkie** [comment] 2024-12-07 20:42
im looking into it, ill report back shortly.

**Comment by Myrkie** [comment] 2024-12-07 21:04
give this [release](https://github.com/Myrkie/BoothDownloader/releases/tag/10.0.6) a try.

**Comment by Kiiinji** [comment] 2024-12-07 21:08
It works! Now let's hope my download doesn't fail..

**Comment by Kiiinji** [comment] 2024-12-07 21:09
Seems like the download speed is the same as on the website
![image](https://github.com/user-attachments/assets/447861b3-318c-41ca-840b-6c0df3c3b2a0)

**Comment by Myrkie** [comment] 2024-12-07 21:11
> It works! Now let's hope my download doesn't fail..
unfortunately I am unable to improve the downloading experience, booth doesn't provide any way to restart downloads if they happen to fail.

> Seems like the download speed is the same as on the website

The download speed is tied to that of your internet service provider and their connection to booth asset servers that is not something any program can fix as its a physical speed between your computer to booth.

**Comment by Myrkie** [comment] 2024-12-07 21:12
fixed by 
> give this [release](https://github.com/Myrkie/BoothDownloader/releases/tag/10.0.6) a try.

**Comment by Kiiinji** [comment] 2024-12-07 21:13
The app crashed during download, just like when I download from the website :(

It worked in the past, Idk what's happening

**Comment by Myrkie** [comment] 2024-12-07 21:16
how is it crashing? does the program close? does it provide any errors? if the download is just failing there's not much that I can do as that is a issue between your Internet service provider and booth.pm a program cannot fix poor internet quality.

**Comment by Kiiinji** [comment] 2024-12-07 21:18
My internet is really good tho
![image](https://github.com/user-attachments/assets/6ffb9eac-b5cb-40b1-b8b9-72669df1674a)
![image](https://github.com/user-attachments/assets/c8283b48-87c5-44b6-ac0c-5e9ad2e6f2d1)

**Comment by Myrkie** [comment] 2024-12-07 21:22
these speed tests are to dedicated servers that show a general maximum speed (in the best possible circumstances), this doesn't mean that every service will be fast, just the ones you are connecting currently too for the speed test. You may have a good connection to speedtest.net for example but that doesn't mean you have a good connection with booth.pm see [BGP peering](https://www.kentik.com/kentipedia/what-is-internet-peering/). there is nothing I can do here.

**Closed as completed by Myrkie** 2024-12-07 21:22 UTC
